# Generated by Django 3.2.4 on 2022-01-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_room_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_song',
            field=models.CharField(default='ASDF', max_length=50),
            preserve_default=False,
        ),
    ]
